### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by benoitlahoz**
Created a typescript `index.d.ts` file with `node-libpd` types. 
For documentation, I basically took original comments and corrected a few typos in it.

### CODE REVIEW

**Comment by b-ma** [comment]
Hey,

Thanks for the work! I will try to merge and publish this during the week

**Comment by benoitlahoz** [comment]
Thank you! I have a bit of work to do. I'm exploring tests and I realize that all types are not exact.

**Comment by benoitlahoz** [comment]
I guess it's OK now. I've been a bit confused about the Audio Input test (not working on my side, but that's another question).

**Comment by b-ma** [comment]
Hey, are we good to proceed, or do you still want to update things?

**Comment by b-ma** [comment]
Released in node-libpd@1.2.0, could you confirm everything works as expected? 

Thanks again

**Comment by benoitlahoz** [comment]
Sorry for the very late answer: yes, it works as expected!

**Pull request merged**
